-- Rollback script for KHADIJA-TUL-QUBRAH BY Meer&Mus
-- Reverses initial migration

DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "lead_activities" CASCADE;
DROP TABLE IF EXISTS "leads" CASCADE;
DROP TABLE IF EXISTS "campaigns" CASCADE;
DROP TABLE IF EXISTS "shipments" CASCADE;
DROP TABLE IF EXISTS "quality_checks" CASCADE;
DROP TABLE IF EXISTS "production_updates" CASCADE;
DROP TABLE IF EXISTS "production_jobs" CASCADE;
DROP TABLE IF EXISTS "payments" CASCADE;
DROP TABLE IF EXISTS "order_items" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
DROP TABLE IF EXISTS "quotation_items" CASCADE;
DROP TABLE IF EXISTS "quotations" CASCADE;
DROP TABLE IF EXISTS "design_files" CASCADE;
DROP TABLE IF EXISTS "custom_design_requests" CASCADE;
DROP TABLE IF EXISTS "product_variants" CASCADE;
DROP TABLE IF EXISTS "product_images" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "craft_options" CASCADE;
DROP TABLE IF EXISTS "fabrics" CASCADE;
DROP TABLE IF EXISTS "size_charts" CASCADE;
DROP TABLE IF EXISTS "sizes" CASCADE;
DROP TABLE IF EXISTS "colours" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "brand_assets" CASCADE;
DROP TABLE IF EXISTS "brand" CASCADE;
DROP TABLE IF EXISTS "agent_profiles" CASCADE;
DROP TABLE IF EXISTS "customer_profiles" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TYPE IF EXISTS "PaymentStatus" CASCADE;
DROP TYPE IF EXISTS "LeadStatus" CASCADE;
DROP TYPE IF EXISTS "ProductionStatus" CASCADE;
DROP TYPE IF EXISTS "OrderStatus" CASCADE;
DROP TYPE IF EXISTS "QuotationStatus" CASCADE;
DROP TYPE IF EXISTS "CustomRequestStatus" CASCADE;
DROP TYPE IF EXISTS "UserRole" CASCADE;
